version: 0.0
os: linux
files:
  - source: /
    destination: /opt/simple-reddit
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/start_server.sh
    - location: scripts/create_test_db.sh
  ApplicationStop:
    - location: scripts/stop_server.sh
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 20
